extraEnvVars:
  - name: SPRING_CONFIG_NAME
    value: "esignet"
  - name: SPRING_CONFIG_LOCATION
    value: "/home/mosip/esignet-local.properties"
  - name: spring_profiles_active
    value: "local"
  - name: mosip.esignet.integration.scan-base-package
    value: "io.mosip.esignet.mock.integration,io.mosip.authentication.esignet.integration"

enable_insecure: false

istio:
  enabled: true
  gateways:
    - name: esignet/esignet-gateway
      protocol: HTTPS
      port: 443
      tls:
        mode: SIMPLE
        credentialName: dev-com-tls
      hosts:
        - DOMAIN
  prefix: /v1/esignet/

serviceMonitor:
  enabled: false

metrics:
  enabled: false

extraEnvVarsCM:
  - artifactory-share
  - softhsm-share